import os
from datetime import datetime

def generate_html_report(risk_list):
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    # Fixed filename to prevent clutter
    filename = "Crisis_Briefing_Latest.html"
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>INTELLIGENCE BRIEFING</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; background: #f4f6f9; padding: 40px; color: #333; }}
            .container {{ max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); border-top: 8px solid #d9534f; }}
            .header {{ border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }}
            .header h1 {{ margin: 0; color: #d9534f; font-size: 24px; text-transform: uppercase; }}
            
            .ai-box {{ background: #e3f2fd; border-left: 5px solid #2196f3; padding: 15px; margin-bottom: 25px; border-radius: 4px; }}
            .ai-title {{ color: #1976d2; font-weight: bold; font-size: 13px; text-transform: uppercase; margin-bottom: 5px; }}
            .ai-text {{ font-size: 15px; line-height: 1.5; color: #0d47a1; }}
            
            .topic-header {{ font-size: 18px; font-weight: bold; color: #c9302c; margin-bottom: 10px; display: flex; align-items: center; justify-content: space-between;}}
            
            ul {{ list-style: none; padding: 0; }}
            li {{ margin-bottom: 12px; border-bottom: 1px solid #eee; padding-bottom: 12px; }}
            .headline {{ font-weight: 600; font-size: 15px; display: block; margin-bottom: 4px; }}
            .meta {{ font-size: 12px; color: #888; }}
            a {{ color: #007bff; text-decoration: none; font-weight: 500; }}
            a:hover {{ text-decoration: underline; }}
            
            .badge {{ background: #d9534f; color: white; padding: 2px 8px; border-radius: 10px; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1> Critical Risk Briefing</h1>
                <div style="color: #888;">{timestamp_str}</div>
            </div>
            <p style="color: #666; margin-bottom: 30px;">
                <strong>CONFIDENTIAL:</strong> The following anomalies were detected by the autonomous agent.
            </p>
    """

    for item in risk_list:
        user_info = ""
        if 'users_affected' in item and item['users_affected']:
             user_info = f"<span class='badge'>Affects {len(item['users_affected'])} Users</span>"

        # Correctly fetching the summary we mapped in agent.py
        summary_text = item.get('ai_assessment', "Summary not available.")

        html_content += f"""
            <div style="margin-bottom: 40px; border: 1px solid #e1e4e8; padding: 20px; border-radius: 8px;">
                <div class="topic-header">
                    <span>TOPIC: {item['topic']}</span>
                    {user_info}
                </div>
                
                <div class="ai-box">
                    <div class="ai-title">⚡ EXECUTIVE SUMMARY (Source: Lead Article)</div>
                    <div class="ai-text">{summary_text}</div>
                </div>

                <div style="font-weight: bold; margin-bottom: 15px; color: #555;">📝 Source Evidence (Click to Verify):</div>
                <ul>
        """
        
        for article in item.get('articles_data', []): 
            title = article.get('title', 'Unknown Title')
            url = article.get('url', '#')
            source = article.get('source_name', 'Source')
            date = article.get('published_date', '')[:10] if article.get('published_date') else ''
            
            html_content += f"""
                <li>
                    <a href="{url}" target="_blank" class="headline">{title} 🔗</a>
                    <div class="meta">{source} • {date}</div>
                </li>
            """
        
        html_content += """
                </ul>
            </div>
        """

    html_content += """
            <div style="text-align: center; color: #aaa; font-size: 12px; margin-top: 40px;">
                GENERATED BY NEWSPULSE AUTONOMOUS AGENT
            </div>
        </div>
    </body>
    </html>
    """

    file_path = os.path.join(os.getcwd(), filename)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    return file_path